### PR TITLE
Always use --debug for db purge

### PR DESCRIPTION
**Pull request by gibizer**

### CODE REVIEW

**Comment by Akrog** [comment]
We already dropped the debug struct, so we should be able to drop this PR.
If I'm wrong, please feel free to re-open it.

**Comment by gibizer** [comment]
> We already dropped the debug struct, so we should be able to drop this PR. If I'm wrong, please feel free to re-open it.

I totally forgot this. After rebase I still see meaningful content in this PR.

**Comment by ASBishop** [comment]
> > We already dropped the debug struct, so we should be able to drop this PR. If I'm wrong, please feel free to re-open it.
> 
> I totally forgot this. After rebase I still see meaningful content in this PR. So I reopened it.

I agree this change makes sense.

**Review by ASBishop — APPROVED** [review]
/lgtm

**Pull request merged**
